site_name: Compliant Kubernetes
site_url: https://compliantkubernetes.io
site_description: >-
  Compliant Kubernetes is a Kubernetes distribution that reduces the burden
  for complying with HIPAA, Swedish Healthcare (Patientdatalagen), GDPR and
  ISO 27001.
site_author: Elastisys AB
copyright: Copyright © 2020 Elastisys AB

repo_url: https://github.com/elastisys/compliantkubernetes
edit_uri: edit/main/docs/

strict: true

theme:
  name: material
  logo: 'img/logo.png'
  favicon: 'img/favicon.png'
  custom_dir: overrides

plugins:
  - include-markdown
  - search

markdown_extensions:
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - Overview: 'index.md'
  - 'Compliance Basics': 'compliance.md'
  - 'Architecture': 'architecture.md'
  - 'Getting Started': 'getting-started.md'
  - 'Exploring Benefits': 'benefits.md'
  - 'User Guide':
    - 'Overview': 'user-guide/index.md'
    - 'Harbor': 'user-guide/harbor.md'
    - 'Kubernetes API': 'user-guide/kubernetes-api.md'
    - 'Logs': 'user-guide/logs.md'
    - 'Metrics': 'user-guide/metrics.md'
    - 'Backups': 'user-guide/backup.md'
    - 'CI/CD': 'user-guide/ci-cd.md'
    - 'Can I?': 'user-guide/demarcation.md'
  - 'CISO Guide':
    - 'Overview': 'ciso-guide/index.md'
    - 'Backup': 'ciso-guide/backup.md'
    - 'Cryptography': 'ciso-guide/cryptography.md'
    - 'Intrusion Detection': 'ciso-guide/intrusion-detection.md'
    - 'Policy-as-Code': 'ciso-guide/policy-as-code.md'
    - 'Network Security': 'ciso-guide/network-security.md'
    - 'Kubernetes Status': 'ciso-guide/kubernetes-status.md'
    - 'Vulnerability Management': 'ciso-guide/vulnerability.md'
  - 'Administrator Manual':
    - 'Overview': 'operator-manual/index.md'
    - 'Getting Started': 'operator-manual/getting-started.md'
    - 'Creating/Destroying/Upgrading a Cluster':
      - 'On AWS': 'operator-manual/aws.md'
      - 'On Azure': 'operator-manual/azure.md'
      - 'On Exoscale': 'operator-manual/exoscale.md'
      - 'On GCP': 'operator-manual/gcp.md'
      - 'On Openstack': operator-manual/openstack.md
      - 'On OVH Managed Kubernetes': 'operator-manual/ovh-managed-kubernetes.md'
      - 'On EKS-D': 'operator-manual/eksd.md'
      - 'Remove Compliant Kubernetes Apps': 'operator-manual/clean-up.md'
    - 'QA': 'operator-manual/qa.md'
    - 'Configuring a Cluster':
      - 'Overview' : 'operator-manual/overview.md'
      - 'Sizing' : 'operator-manual/cluster-sizing.md'
      - 'Ingress': 'operator-manual/ingress.md'
      - 'Access Control': 'operator-manual/access-control.md'
    - 'Disaster Recovery': 'operator-manual/disaster-recovery.md'
    - 'Breaking the Glass': 'operator-manual/break-glass.md'
    - 'Use of Credentials': 'operator-manual/credentials.md'
    - 'Troubleshooting': 'operator-manual/troubleshooting.md'
  - 'Developer Guide':
    - 'Tech Radar': 'developer-guide/tech-radar/index.html'
    - 'Contributor guide': 'developer-guide/contributor-guide.md'
    - 'Architectural Decision Log': 'adr/index.md'
  - 'Vocabulary': 'vocabulary.md'
  - 'FAQ': 'faq.md'
  - 'Roadmap': 'roadmap.md'
  - 'Support ⧉': 'https://compliantkubernetes.com/'
  - 'Blog ⧉': 'https://elastisys.com/blog/'
