site_name: Compliant Kubernetes
site_url: https://elastisys.io/
site_description: >-
  Compliant Kubernetes is a Kubernetes distribution that reduces the burden
  for complying with Swedish Healthcare (Patientdatalagen), GDPR and
  ISO 27001.
site_author: Elastisys AB
copyright: Copyright © 2020 Elastisys AB

repo_url: https://github.com/elastisys/compliantkubernetes
edit_uri: edit/main/docs/

strict: true

theme:
  name: material
  font: false
  logo: 'img/logo.png'
  favicon: 'img/favicon.png'
  custom_dir: overrides

plugins:
  - include-markdown
  - search

markdown_extensions:
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
      toc_depth: '2'
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Overview: 'index.md'
  - 'Compliance Basics': 'compliance.md'
  - 'Getting Started': 'getting-started.md'
  - 'User Guide':
    - 'Overview': 'user-guide/index.md'
    - 'Set up': 'user-guide/setup.md'
    - 'Prepare Your Application': 'user-guide/prepare.md'
    - 'Container registry': 'user-guide/registry.md'
    - 'Kubernetes API': 'user-guide/kubernetes-api.md'
    - 'Logs': 'user-guide/logs.md'
    - 'Metrics': 'user-guide/metrics.md'
    - 'Alerts': 'user-guide/alerts.md'
    - 'Backups': 'user-guide/backup.md'
    - 'CI/CD': 'user-guide/ci-cd.md'
    - 'Safeguards': 'user-guide/safeguards.md'
    - 'Can I?': 'user-guide/demarcation.md'
    - 'Go-live Checklist': 'user-guide/go-live.md'
  - 'CISO Guide':
    - 'Overview': 'ciso-guide/index.md'
    - 'Backup': 'ciso-guide/backup.md'
    - 'Cryptography': 'ciso-guide/cryptography.md'
    - 'Intrusion Detection': 'ciso-guide/intrusion-detection.md'
    - 'Policy-as-Code': 'ciso-guide/policy-as-code.md'
    - 'Network Security': 'ciso-guide/network-security.md'
    - 'Kubernetes Status': 'ciso-guide/kubernetes-status.md'
    - 'Vulnerability Management': 'ciso-guide/vulnerability.md'
    - 'Log Review': 'ciso-guide/log-review.md'
  - 'Administrator Manual':
    - 'Overview': 'operator-manual/index.md'
    - 'Getting Started': 'operator-manual/getting-started.md'
    - 'Creating/Destroying/Upgrading a Cluster':
      - 'On AWS': 'operator-manual/aws.md'
      - 'On Azure': 'operator-manual/azure.md'
      - 'On Exoscale': 'operator-manual/exoscale.md'
      - 'On GCP': 'operator-manual/gcp.md'
      - 'On Openstack': 'operator-manual/openstack.md'
      - 'On Safespring': 'operator-manual/safespring.md'
      - 'On OVH Managed Kubernetes': 'operator-manual/ovh-managed-kubernetes.md'
      - 'On EKS-D': 'operator-manual/eksd.md'
      - 'Remove Compliant Kubernetes Apps': 'operator-manual/clean-up.md'
    - 'QA': 'operator-manual/qa.md'
    - 'Configuring a Cluster':
      - 'Overview' : 'operator-manual/overview.md'
      - 'Sizing' : 'operator-manual/cluster-sizing.md'
      - 'Ingress': 'operator-manual/ingress.md'
      - 'Access Control': 'operator-manual/access-control.md'
      - 'User Alerts': 'operator-manual/user-alerts.md'
    - 'Disaster Recovery': 'operator-manual/disaster-recovery.md'
    - 'Breaking the Glass': 'operator-manual/break-glass.md'
    - 'Use of Credentials': 'operator-manual/credentials.md'
    - 'Troubleshooting': 'operator-manual/troubleshooting.md'
  - 'Contributor Guide':
    - 'Overview': 'contributor-guide/index.md'
    - 'Architecture': 'architecture.md'
    - 'Architectural Decision Log': 'adr/index.md'
    - 'Tech Radar': 'tech-radar/index.html'
  - 'Vocabulary': 'vocabulary.md'
  - 'FAQ': 'faq.md'
  - 'Release Notes': 'release-notes.md'
  - 'Roadmap': 'roadmap.md'
  - 'Support ⧉': 'https://elastisys.com/'
  - 'Blog ⧉': 'https://elastisys.com/blog/'
